
#
# Tag representation for dir, group, filename
#    <HOSTNAME> -> hostname of current machine
#    <APP> -> binary file name of current application
#    <LOG> -> the name of current logger, in default cfg, the name is 'default'
#
#  note: 
#    1. the key like 'dir', 'group', ... under elog directly is to set default value,
#       you do not need to set it because all of them have a default value inside
#    2. for 'level', 'stack_level', 'color' you set only one val for console and file
#       settings, or you can set a arr with two val to set config for console and file
#       respectively 
#

elog_:
  dir           : logs                    # default logs
  group         : <HOSTNAME>              # default <HOSTNAME>, if set, real dir will be $Dir/$Group
  filename      : <LOG_NAME>              # default <LOG_NAME>, will not write to file if set empty, real file path will be $Dir/$Group/$File
  max_size      : 100                     # default 100, unit MB
  max_backups   : 7                       # default 7
  max_age       : 7                       # default 7
  compress      : false                   # default false
  level         : [info,  debug]          # default info , debug, [0] for console, [1] for file, valid value is [debug, info, warn, error, fatal, panic]
  stack_level   : [fatal, warn ]          # default fatal, warn , [0] for console, [1] for file, valid value is [debug, info, warn, error, fatal, panic]
  color         : [true,  false]          # default true , true , [0] for console, [1] for file

  nofile: 
    filename: ""

  setfile: {}

  level_debug:
    level   : debug

elog:
  
  dir           : logs                # default logs
  group         : <HOSTNAME>          # default <HOSTNAME>, if set, real dir will be $Dir/$Group
  filename      : <APP>_<LOG>         # default <LOG_NAME>, will not write to file if set empty, real file path will be $Dir/$Group/$File
  max_size      : 100                 # default 100, unit MB
  max_backups   : 7                   # default 7
  max_age       : 7                   # default 7
  compress      : false               # default false
  f_level       : debug               # default debug, for file, valid value is [debug, info, warn, error, fatal, panic]
  f_stack_level : warn                # default warn , for file, valid value is [debug, info, warn, error, fatal, panic]
  f_color       : false               # default false, for file
  c_level       : debug                # default info , for console, valid value is [debug, info, warn, error, fatal, panic]
  c_stack_level : warn               # default error, for console, valid value is [debug, info, warn, error, fatal, panic]
  c_color       : true                # default true , for console

  default:
  - name        : console
    stream      : stdout
    level       : info
    stack_level : error
    color       : auto                # auto[default], true, false
  - name        : file
    dir         : logs                # default logs
    group       : <HOSTNAME>          # default <HOSTNAME>, if set, real dir will be $dir/$group
    filename    : <APP>_<LOG>         # default <LOG_NAME>, will not write to file if set empty, real file path will be $dir/$group/$file_name
    max_size    : 100                 # default 100, unit MB
    max_backup  : 7                   # default 7
    max_age     : 7                   # default 7
    compress    : false               # default false
    level       : debug               # default debug, for file, valid value is [debug, info, warn, error, fatal, panic]
    stack_level : warn                # default warn , for file, valid value is [debug, info, warn, error, fatal, panic]
    color       : false               # default false, for file

  console:
  - stream: stdout

  file:
  - filename: <APP>_<LOG>
  
  mix:
  - inherit: console.0
  - inherit: file.0

