package elog

import (
	"go.uber.org/zap"
)

type Elog = *zap.SugaredLogger

// Log - get a log generated by DfLogger()
// the passed in option have high priority, if no options passed, it returned a default Elog
func Log(options ...Option) Elog {
	return Logger().Log(options...)
}